=== cqg21/mitlab-workflow/mitlab-workflow-jdbc/src/test/resources/workflows/mitlab-workflow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.mitlab.org/workflow" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:mw="http://www.mitlab.org/workflow">

    <element name="workflow" type="mw:WorkflowDescriptor"></element>
    
    <complexType name="WorkflowDescriptor">
    	<sequence>
    		<element name="start-step" type="mw:StepDescriptor"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="step" type="mw:StepDescriptor" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="stop-step" type="mw:StepDescriptor"
    			minOccurs="1" maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="StepDescriptor">
    	<sequence>
    		<element name="meta" type="mw:MetaDescriptor" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="pre-functions"
    			type="mw:FunctionsDescriptor" minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="actions" type="mw:ActionsDescriptor" minOccurs="0" maxOccurs="1"></element>
    		<element name="post-functions"
    			type="mw:FunctionsDescriptor" minOccurs="0" maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="name" type="string"></attribute>
    </complexType>


    <complexType name="ActionDescriptor">
    	<sequence>
    		<element name="meta" type="mw:MetaDescriptor" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="conditions" type="mw:ConditionsDescriptor" minOccurs="0" maxOccurs="1"></element>
    		<element name="pre-functions" type="mw:FunctionsDescriptor"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="results" type="mw:ResultsDescriptor" minOccurs="1" maxOccurs="1"></element>
    		<element name="post-functions"
    			type="mw:FunctionsDescriptor" minOccurs="0" maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="name" type="string"></attribute>
    </complexType>
    
    <complexType name="MetaDescriptor">
    	<attribute name="key" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>

    <complexType name="ActionsDescriptor">
    	<sequence>
    		<element name="action" type="mw:ActionDescriptor" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="FunctionsDescriptor">
    	<sequence>
    		<element name="function" type="mw:FunctionDescriptor" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="FunctionDescriptor">
    	<sequence>
    		<element name="arg" type="mw:ArgDescriptor" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="spring"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="ArgDescriptor">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>

    <complexType name="ConditionsDescriptor">
    	<sequence>
    		<element name="condition" type="mw:ConditionDescriptor"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="conditions" type="mw:ConditionsDescriptor" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="AND"></enumeration>
    				<enumeration value="OR"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="ResultsDescriptor">
    	<sequence>
    		<element name="result" type="mw:ResultDescriptor" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="ResultDescriptor">
    	<sequence>
    		<element name="meta" type="mw:MetaDescriptor" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="conditions" type="mw:ConditionsDescriptor"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="pre-functions" type="mw:FunctionsDescriptor"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="post-functions" type="mw:FunctionsDescriptor"
    			minOccurs="0" maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="old-status" type="string"></attribute>
    	<attribute name="status" type="string"></attribute>
    	<attribute name="step" type="string"></attribute>
    	<attribute name="user-group" type="string"></attribute>
    	<attribute name="subflows" type="string"></attribute>
    </complexType>

    <complexType name="ConditionDescriptor">
    	<sequence>
    		<element name="arg" type="mw:ArgDescriptor" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="spring"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>
</schema>

=== cqg21/mitlab-workflow/mitlab-workflow-jdbc/src/test/resources/workflows/mitlab-workflow.bak.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow xmlns="http://www.mitlab.org/workflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mitlab.org/workflow mitlab-workflow.xsd "
	name="workflow_bak">
	<start-step id="startStep" name="创建DEMO申请单">
		<actions>
			<action id="act_startStep" name="创建">
				<meta key="act_startStep" value="act_startStep" />
				<conditions type="OR">
					<condition type="spring">
						<arg name="bean.id" value="PermissionCondition"/>
						<arg name="permission" value="security:index"/>
					</condition>
				</conditions>
				<results>
					<result old-status="Finish" status="running" user-group="demoUserGroup" step="secondStep">
						<pre-functions>
							<function type="spring">
								<arg name="bean.id" value="TestStepUserFunction" />
							</function>
						</pre-functions>
					</result>
				</results>
			</action>
		</actions>
	</start-step>
	
	<step id="secondStep" name="研发部审批">
		<meta key="editAdvise" value="true" />
		<meta key="editRemark" value="true" />
		<meta key="redoRemark" value="true"/>
		<actions>
			<action id="act_secondStep_001" name="同意">
				<results>
					<result name="会签" old-status="MoreThanOneStepUserCondition" status="running" step="secondStep" user-group="secondStep">
						<conditions>
							<condition type="spring">
								<arg name="bean.id" value="MoreThanOneStepUserCondition" />
							</condition>
						</conditions>
						<pre-functions>
							<function type="spring">
								<arg name="bean.id" value="LayoffStepUserFunction" />
								<arg name="group" value="demoUserGroup"/>
							</function>
						</pre-functions>
					</result>
					<result name="会签结束" old-status="stopStep" status="running" step="thirdStep" user-group="thirdStep"/>
				</results>
			</action>
		</actions>
	</step>
	
	<step id="thirdStep" name="质量保障部审批">
		<meta key="editAdvise" value="false" />
		<meta key="editRemark" value="true" />
		<actions>
			<action id="act_thirdStep_001" name="同意">
				<meta key="act_thirdStep_001" value="act_thirdStep_001" />
				<results>
					<!-- <result old-status="stopStep" status="running" step="fourStep" user-group="stopStep"/> -->
					<result old-status="stopStep" status="running" step="fourStep" user-group="stopStep" subflows="subflow-d1,subflow-d2"/>
				</results>
			</action>
			<action id="act_thirdStep_002" name="退回">
				<meta key="act_thirdStep_001" value="act_thirdStep_001" />
				<results>
					<result old-status="stopStep" status="running" step="secondStep" user-group="stopStep">
						<pre-functions>
							<function type="spring">
								<arg name="bean.id" value="LastStepCallerFunction"/>
							</function>
						</pre-functions>
					</result>
				</results>
			</action>
			<action id="act_thirdStep_003" name="终止">
				<meta key="act_thirdStep_001" value="act_thirdStep_001" />
				<results>
					<result old-status="stopStep" status="running" step="stopStep" user-group="stopStep"/>
				</results>
			</action>
		</actions>
	</step>
	
	<step id="fourStep" name="公司管理层审批">
		<meta key="editAdvise" value="true" />
		<meta key="editRemark" value="true" />
		<actions>
			<action id="act_thirdStep_001" name="同意">
				<conditions>
					<condition type="spring">
						<arg name="bean.id" value="JoinCondition"/>
					</condition>
				</conditions>
				<meta key="act_thirdStep_001" value="act_thirdStep_001" />
				<results>
					<result old-status="stopStep" status="running" step="fiveStep" user-group="stopStep"/>
				</results>
			</action>
		</actions>
	</step>
	
	<step id="fiveStep" name="总裁办审批">
		<meta key="editAdvise" value="true" />
		<meta key="editRemark" value="true" />
		<actions>
			<action id="fiveStep-ACT_001" name="同意">
				<meta key="fiveStep-ACT_001" value="act_thirdStep_001" />
				<results>
					<result old-status="stopStep" status="running" step="stopStep" user-group="stopStep"/>
				</results>
			</action>
			<action id="fiveStep-ACT_002" name="退回">
				<meta key="fiveStep-ACT_001" value="act_thirdStep_001" />
				<results>
					<result old-status="stopStep" status="running" step="fourStep" user-group="stopStep">
						<pre-functions>
							<function type="spring">
								<arg name="bean.id" value="LastStepCallerFunction"/>
							</function>
						</pre-functions>
					</result>
				</results>
			</action>
			<action id="fiveStep-ACT_003" name="退回研发部">
				<meta key="fiveStep-ACT_001" value="act_thirdStep_001" />
				<results>
					<result old-status="stopStep" status="running" step="secondStep" user-group="stopStep">
						<pre-functions>
							<function type="spring">
								<arg name="bean.id" value="LastStepCallerFunction"/>
							</function>
						</pre-functions>
					</result>
				</results>
			</action>
		</actions>
	</step>
	
	<stop-step id="stopStep" name="DEMO申请单结束" />
</workflow>

=== cqg21/mitlab-workflow/mitlab-workflow-jdbc/src/test/resources/workflows/mitlab-subflow-d1.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow xmlns="http://www.mitlab.org/workflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mitlab.org/workflow mitlab-workflow.xsd "
	name="subflow-d1">
	<start-step id="startStep" name="启动行政部子流程">
		<actions>
			<action id="startStep_act_01" name="启动">
				<conditions type="OR">
					<condition type="spring">
						<arg name="bean.id" value="PermissionCondition"/>
						<arg name="permission" value="security:index"/>
					</condition>
				</conditions>
				<results>
					<result old-status="Finish" status="running" user-group="demoUserGroup" step="secondStep"/>
				</results>
			</action>
		</actions>
	</start-step>
	
	<step id="secondStep" name="行政部审批">
		<meta key="editAdvise" value="false" />
		<meta key="editRemark" value="true" />
		<actions>
			<action id="secondStep_act_001" name="同意">
				<results>
					<result old-status="stopStep" status="running" step="stopStep" user-group="stopStep"/>
				</results>
			</action>
		</actions>
	</step>
	
	<stop-step id="stopStep" name="结束行政部子流程" />
</workflow>

=== cqg21/mitlab-workflow/mitlab-workflow-jdbc/src/test/resources/workflows/requisition-workflow.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow xmlns="http://www.mitlab.org/workflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mitlab.org/workflow mitlab-workflow.xsd "
	name="requisition">
	<start-step id="startStep" name="创建申请单">
		<actions>
			<action id="act_startStep" name="创建">
				<meta key="act_startStep" value="act_startStep" />
				<conditions type="OR">
					<condition type="spring">
						<arg name="bean.id" value="PermissionCondition"/>
						<arg name="permission" value="security:index"/>
					</condition>
				</conditions>
				<results>
					<result old-status="Finish" status="running" user-group="demoUserGroup" step="secondStep">
						<pre-functions>
							<function type="spring">
								<arg name="bean.id" value="TestStepUserFunction" />
							</function>
                            <function type="spring">
                                <arg name="bean.id" value="SaveArgumentsPreFunction"/>
                            </function>
						</pre-functions>
					</result>
				</results>
			</action>
		</actions>
	</start-step>
	
	<step id="secondStep" name="审批">
		<meta key="editAdvise" value="false" />
		<meta key="editRemark" value="true" />
		<actions>
			<action id="act_thirdStep_001" name="同意">
				<meta key="act_thirdStep_001" value="act_thirdStep_001" />
                <pre-functions>
                    <function type="spring">
                        <arg name="bean.id" value="SaveArgumentsPreFunction"/>
                    </function>
                </pre-functions>
				<results>
					<result old-status="stopStep" status="running" step="stopStep" user-group="stopStep"/>
				</results>
			</action>
			<action id="act_thirdStep_002" name="不同意">
				<meta key="act_thirdStep_001" value="act_thirdStep_001" />
				<results>
					<result old-status="stopStep" status="running" step="stopStep" user-group="stopStep">
						<!-- <pre-functions>
							<function type="spring">
								<arg name="bean.id" value="LastStepCallerFunction"/>
							</function>
						</pre-functions> -->
					</result>
				</results>
			</action>
		</actions>
	</step>
	
	<stop-step id="stopStep" name="申请单流程结束" />
</workflow>
